# Generated by Django 3.2.19 on 2023-07-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230709_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingridient',
            new_name='ingridients',
        ),
    ]
